export const FETCH_POST = 'FETCH_POST';
export const ADD_POST = 'ADD_POST';
export const SET_LOADING = 'SET_LOADING';
// export const FETCH_POST = 'FETCH_POST';
// export const FETCH_POST = 'FETCH_POST';
// export const FETCH_POST = 'FETCH_POST';
// export const FETCH_POST = 'FETCH_POST';
// export const FETCH_POST = 'FETCH_POST';
// export const FETCH_POST = 'FETCH_POST';
